version: '3.9'

services:
  web:
    user: root
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app/
      - static_volume:/static/
      - media_volume:/media/
    ports:
      - 8000:8000
    env_file:
      - ./.env
  db-dev:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - 5436:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
  static_volume:
  media_volume: