version: '3.9'

services:
  web:
    user: root
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app/
      - static_volume:/static/
      - media_volume:/media/
    ports:
      - 8000:8000

volumes:
  static_volume:
  media_volume: