# Generated by Django 4.1.5 on 2023-01-11 23:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_name_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
